### ISSUE TITLE
GoogleGenerativeAIError: [404 Not Found]

### ISSUE THREAD

**Issue by coloz** [google/generative-ai-js#10]
## Expected Behavior
-
## Actual Behavior
GoogleGenerativeAIError: [404 Not Found]
    at makeRequest (file:///D:/git/aily-project/gpt-api/node_modules/@google/generative-ai/dist/index.mjs:205:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContentStream (file:///D:/git/aily-project/gpt-api/node_modules/@google/generative-ai/dist/index.mjs:505:22)
    at async GeminiClient.sendMessage (file:///D:/git/aily-project/gpt-api/client/GeminiClient.js:62:24)
    at async Object.<anonymous> (file:///D:/git/aily-project/gpt-api/app.js:215:22)
GoogleGenerativeAIError: [404 Not Found]
    at makeRequest (file:///D:/git/aily-project/gpt-api/node_modules/@google/generative-ai/dist/index.mjs:205:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContentStream (file:///D:/git/aily-project/gpt-api/node_modules/@google/generative-ai/dist/index.mjs:505:22)
    at async GeminiClient.sendMessage (file:///D:/git/aily-project/gpt-api/client/GeminiClient.js:62:24)
    at async Object.<anonymous> (file:///D:/git/aily-project/gpt-api/app.js:215:22)

## Steps to Reproduce the Problem
```
        let gemini = new GoogleGenerativeAI(process.env.GEMINI_API_KEY).getGenerativeModel({
            model: "gemini-pro",
            generationConfig: {
                temperature: this.temperature
            }
        });
        const result = await gemini.generateContentStream(conversation.messages);
        for await (const chunk of result.stream) {
            const chunkText = chunk.text();
            console.log(chunkText);
            opts.onProgress(chunkText);
            reply += chunkText;
        }
```

## Specifications

- Version: nodejs v18.16.0
- Platform: windows

**Comment by hsubox76** [comment]
Are you formatting the error? When it throws the error it should be surrounded by some additional text and the url: https://github.com/google/generative-ai-js/blob/main/packages/main/src/requests/request.ts#L88C1-L88C1

I'm not sure why it's not showing up in that message, but do you have some other way to identify the url it's trying to call? That would be really helpful. (You can remove your API key)
