### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by logankilpatrick** [google/generative-ai-js#49]
## Expected Behavior

Trying to run the example here: https://github.com/google/generative-ai-js/tree/main?tab=readme-ov-file#try-out-a-sample-app

## Actual Behavior

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

ReferenceError: fetch is not defined
    at makeRequest (file:///Users/logan/code/generative-ai-js/samples/node/node_modules/@google/generative-ai/dist/index.mjs:193:9)
    at countTokens (file:///Users/logan/code/generative-ai-js/samples/node/node_modules/@google/generative-ai/dist/index.mjs:755:28)
    at GenerativeModel.countTokens (file:///Users/logan/code/generative-ai-js/samples/node/node_modules/@google/generative-ai/dist/index.mjs:853:16)
    at run (file:///Users/logan/code/generative-ai-js/samples/node/simple-text.js:26:39)
    at file:///Users/logan/code/generative-ai-js/samples/node/simple-text.js:35:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
logan@oai-logan node % ls -l
```

## Steps to Reproduce the Problem

Walked through the steps here: https://github.com/google/generative-ai-js/tree/main?tab=readme-ov-file#try-out-a-sample-app

## Specifications

- Version: Node v16.13.0
- Platform: MacOS

**Comment by alx13** [comment]
This library requires Node.js >=18.0.0 because it uses Fetch API and it as only released in that version.
