### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by arokhsaz3** [google/generative-ai-js#6]
Hey, I'm having an issue within the demo for https://ai.google.dev/tutorials/node_quickstart#generate-text-from-text-input. I'm not able to run the demo in Nodejs.

Output:
The error was:  ReferenceError: fetch is not defined
    at makeRequest Nodejs/node_modules/@google/generative-ai/dist/index.js:187:9)
    at generateContent (Nodejs/node_modules/@google/generative-ai/dist/index.js:511:28)
    at GenerativeModel.generateContent (Nodejs/node_modules/@google/generative-ai/dist/index.js:785:16)
    at run (Nodejs/controllers/bard-controller.js:18:30)
    at Object.<anonymous> (Nodejs/controllers/bard-controller.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

## Code from my end
const { GoogleGenerativeAI } = require("@google/generative-ai");

// Access your API key as an environment variable (see "Set up your API key" above)
const genAI = new GoogleGenerativeAI(API_KEY);

async function run() {
  // For text-only input, use the gemini-pro model
  const model = genAI.getGenerativeModel({ model: "gemini-pro"});

  const prompt = "Write a story about a magic backpack."

  const result = await model.generateContent(prompt);
  const response = await result.response;
  const text = response.text();
  console.log(text);
}

**Comment by lahirumaramba** [comment]
What's your Node.js version? The SDK requires Node.js 18+

**Comment by NibiewJ** [comment]
> What's your Node.js version? The SDK requires Node.js 18+

Node.js v18.19.0

The Error Stack:

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (/path/to/gemini-demo/node_modules/@google/generative-ai/dist/index.js:187:20)
    at async generateContent (/path/to/gemini-demo/node_modules/@google/generative-ai/dist/index.js:511:22)
    at async run (/path/to/gemini-demo/index.js:12:18)

Node.js v18.19.0

**Comment by iProgramme** [comment]
> > What's your Node.js version? The SDK requires Node.js 18+
> 
> Node.js v18.19.0
> 
> The Error Stack:
> 
> node:internal/process/promises:288 triggerUncaughtException(err, true /* fromPromise */); ^
> 
> TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11730:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async makeRequest (/path/to/gemini-demo/node_modules/@google/generative-ai/dist/index.js:187:20) at async generateContent (/path/to/gemini-demo/node_modules/@google/generative-ai/dist/index.js:511:22) at async run (/path/to/gemini-demo/index.js:12:18)
> 
> Node.js v18.19.0

the same error！

**Comment by arokhsaz3** [comment]
Thanks for the help guys, I thought my instance was updated, but it was not. My mistake. I was running v16.

**Comment by iProgramme** [comment]
so how to fix it, I still have this problem：

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (/Users/yubowen/Desktop/MyPrivate/node_modules/@google/generative-ai/dist/index.js:187:20)
    at async generateContentStream (/Users/yubowen/Desktop/MyPrivate/node_modules/@google/generative-ai/dist/index.js:506:22)

Node.js v18.18.0

**Comment by Rocke1001feller** [comment]
Same code，Same error，my nodejs is 18.3.0
![image](https://github.com/google/generative-ai-js/assets/97436317/0677d276-a90a-4fae-b213-637442316c27)

**Comment by dishankjindal1** [comment]
Hey @arokhsaz3 - Can you help me with the same? i am not able run this.

We are building a VS-code extension for https://github.com/dishankjindal1/fluttergpt 
node - 20.6.1 and also tested on latest stable
system - Apple m2 pro

The same issue is not happening on others system using m series. 

```
ReferenceError: fetch is not defined
	at makeRequest (/Users/dishankjindal/projects/personal/others/fluttergpt/node_modules/@google/generative-ai/dist/index.js:195:9)
	at generateContent (/Users/dishankjindal/projects/personal/others/fluttergpt/node_modules/@google/generative-ai/dist/index.js:525:28)
	at /Users/dishankjindal/projects/personal/others/fluttergpt/node_modules/@google/generative-ai/dist/index.js:650:25
	at async ChatSession.sendMessage (/Users/dishankjindal/projects/personal/others/fluttergpt/node_modules/@google/generative-ai/dist/index.js:669:9)
	at async GeminiRepository.getCompletion (/Users/dishankjindal/projects/personal/others/fluttergpt/src/repository/gemini-repository.ts:36:24)
	at async FlutterGPTViewProvider.getResponse (/Users/dishankjindal/projects/personal/others/fluttergpt/out/providers/chat_view_provider.js:87:30) {stack: 'ReferenceError: fetch is not defined
	at make…pt/out/providers/chat_view_provider.js:87:30)', message: '[GoogleGenerativeAI Error]: Error fetching f…ni-pro:generateContent: fetch is not defined'}
```
<img width="497" alt="Screenshot 2023-12-29 at 12 52 50 PM" src="https://github.com/google/generative-ai-js/assets/6309258/3f7b99ac-b470-40a3-b48e-7989752121fa">

Any help is much appreciated.

**Comment by samyakkkk** [comment]
So we were able to resolve the issue. https://stackoverflow.com/a/76440754/13038101. VScode extensions actually use the underlying version of the VSCODE itself and not your system.

@dishankjindal1's VSCODE was on an older version that used v16 of NodeJS. updating vscode solved the issue for us.
